### ISSUE TITLE
sunrise sunset swapped

### ISSUE THREAD

**Issue by Jagsta2121** [bp2008/DahuaSunriseSunset#12]
my sunrise and sunset seem to be flipped
![image](https://user-images.githubusercontent.com/37634872/199026303-b06f0958-ed09-4603-8604-ab77024f054f.png)
it enables the night profile at 6:22 am instead of the day profile.

**Comment by bp2008** [comment]
The coordinates you entered are in central China, but with a time zone in central daylight time.  So it is is working as intended.  Make your longitude negative and you'll probably find the behavior much more to your liking.

**Comment by Jagsta2121** [comment]
oops I apologize google didn't have a - when  I looked it up!
