### ISSUE TITLE
Long/Lat Timezone issue with GMT 0

### ISSUE THREAD

**Issue by Locoblade** [bp2008/DahuaSunriseSunset#2]
If you live in a UTC+00:00 timezone (Dublin, Edinburgh, Lisbon, London) but your location has a negative longitude (West of the meridian line so most of the UK/Ireland and all of Portugal), the following error occurs when clicking View Sunrise/Sunset and the app appears unable to calculate a valid sunrise/sunset time.
![image](https://user-images.githubusercontent.com/43304139/45590805-5aa77b00-b939-11e8-941f-32f1497fc428.png).

**Comment by bp2008** [comment]
Hmm, because during daylight savings that is a +1 timezone and the Lon is negative so this code complains.

**Comment by bp2008** [comment]
I replaced the sunrise/sunset calculation module with a much larger, but more robust one, which I believe adequately solves this problem.  Try version 1.4: https://github.com/bp2008/DahuaSunriseSunset/releases

**Comment by Locoblade** [comment]
Good work, yep just installed the new version and it works fine now :)
